apiVersion: batch/v1
kind: Job
metadata:
  name: 1-test-gang-job
spec:
  parallelism: 4
  template:
    metadata:
      name: test-1
      annotations:
        "firmament-gang-scheduling" : "75"
    spec:
      schedulerName: poseidon
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        resources:
          requests:
           memory: "120Mi"
           cpu: "1200m"
          limits:
            memory: "130Mi"
            cpu: "1300m"
      restartPolicy: Never
