/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: queue_desc.proto

package firmament

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueueDescriptor struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Weight               int32    `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueDescriptor) Reset()         { *m = QueueDescriptor{} }
func (m *QueueDescriptor) String() string { return proto.CompactTextString(m) }
func (*QueueDescriptor) ProtoMessage()    {}
func (*QueueDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_45ea29f44060e4bf, []int{0}
}

func (m *QueueDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueDescriptor.Unmarshal(m, b)
}
func (m *QueueDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueDescriptor.Marshal(b, m, deterministic)
}
func (m *QueueDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueDescriptor.Merge(m, src)
}
func (m *QueueDescriptor) XXX_Size() int {
	return xxx_messageInfo_QueueDescriptor.Size(m)
}
func (m *QueueDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_QueueDescriptor proto.InternalMessageInfo

func (m *QueueDescriptor) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *QueueDescriptor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueueDescriptor) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*QueueDescriptor)(nil), "firmament.QueueDescriptor")
}

func init() { proto.RegisterFile("queue_desc.proto", fileDescriptor_45ea29f44060e4bf) }

var fileDescriptor_45ea29f44060e4bf = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2c, 0x4d, 0x2d,
	0x4d, 0x8d, 0x4f, 0x49, 0x2d, 0x4e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0xcb,
	0x2c, 0xca, 0x4d, 0xcc, 0x4d, 0xcd, 0x2b, 0x51, 0xf2, 0xe7, 0xe2, 0x0f, 0x04, 0x49, 0xbb, 0xa4,
	0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x09, 0x09, 0x70, 0x31, 0x97, 0x66, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x81, 0x98, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x79, 0x6a, 0x66,
	0x7a, 0x46, 0x89, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0x97, 0xc4, 0x06, 0xb6, 0xc2,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xae, 0xaa, 0x9e, 0x42, 0x76, 0x00, 0x00, 0x00,
}
